version: "3.9"

services:
    some-rabbit:
        hostname: "some-rabbit"
        image: rabbitmq:3-management
        ports:
            - 15672:15672
        #     - 5672:5672
        networks:
            - postgres_default
    fast-rabbit:
        depends_on:
            - some-rabbit
        build:
            context: ./
            dockerfile: Dockerfile
        hostname: "fast-rabbit"
        image: fast-rabbit-celery
        ports:
            - 9000:9000
            - 5556:5556
        environment:
            - CELERY_BROKER_URL=amqp://guest:guest@some-rabbit:5672//
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/celery
        volumes:
            - fast-rabbit:/db
        networks:
            - postgres_default

volumes:
    fast-rabbit:
networks:
    postgres_default:
        external: true
